language: node_js
node_js:
  - '7.8.0'
env:
    global:
        - CHROME_BIN="chromium-browser"
        - DISPLAY=:99.0
        - NODE_ENV=test
dist: trusty
cache:
    yarn: true
    directories:
        - node_modules
before_install:
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
    - sh -e /etc/init.d/xvfb start
    - sleep 3
before_script:
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - git config credential.helper "store --file=.git/credentials"
    - echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
    - yarn
    - make build
    - ./nodu_modules/.bin/np prerelease --tag multi-action --any-branch
    - git push origin v1.3.2-with-multi-actions
#branches:
#  only:
#    - master
#    - next
